import { test, expect } from '@playwright/test';

test('test20250114', async ({ page }) => {
await page.goto('await page.goto('https://jp.skyticket.jp/');
await page.getByRole('button', { name: '旅のオプション' }).click();
await page.locator('skyticket-header-nav-item-pc').getByRole('link', { name: '観光ガイド' }).click();
await page.getByRole('link', { name: '北海道' }).click();');
await page.getByRole('button', { name: '航空券' }).click();
await page.locator('skyticket-header-nav-item-pc').getByRole('link', { name: '国内航空券' }).click();
await page.getByText('片道').click();
await page.getByPlaceholder('出発地').click();
await page.locator('li').filter({ hasText: '東京(成田・羽田)(TYO)' }).first().click();
await page.getByPlaceholder('到着地').click();
await page.locator('li').filter({ hasText: '札幌(新千歳)(CTS)' }).nth(2).click();
await page.getByLabel('出発日', { exact: true }).click();
await page.getByTitle('next').dblclick();
await page.getByRole('link', { name: '1', exact: true }).nth(1).click();
await page.locator('#num_of_people').click();
await page.locator('#on_board_adult_num').click();
await page.locator('#on_board_adult_num').fill('1');
await page.locator('#search_form div').filter({ hasText: '保存' }).nth(3).click();
await page.getByRole('button', { name: '最安値を検索' }).click();
await page.getByRole('cell', { name: '日本航空 JAL501 普通席' }).getByRole('img').click();
await page.getByRole('link', { name: 'ログインして予約する方はこちら' }).click();
await page.getByPlaceholder('登録メールアドレス（会員ID用）').click();
await page.getByPlaceholder('登録メールアドレス（会員ID用）').fill('t-xie@adventure-inc.co.jp');
await page.getByRole('textbox', { name: 'パスワード' }).click();
await page.getByRole('textbox', { name: 'パスワード' }).fill('Kani1204');
await page.getByRole('textbox', { name: 'パスワード' }).press('Enter');
await page.getByRole('button', { name: 'ログイン' }).click();
await page.getByText('今すぐ購入').click();
await page.getByRole('button', { name: '申込内容の確認へ' }).click();
await page.getByLabel('上記の内容に同意します').check();
await page.getByRole('button', { name: 'お支払いへ' }).click();
await page.goto('https://dev-pay.skyticket.jp/choice?t=JDJ5JDEWJGRGDEZOTJHXZ1VRCXNXAXLIZDNNLY5LYNJYRXNPEWXMWVL2QJRXRK01Q1KWZ3V2WDZMRMZX');
await page.getByText('クレジットカード').click();
await page.locator('#selectTravelInsurance path').click();
await page.locator('#selectCancelInsurance path').click();
await page.getByPlaceholder('例: 0000000000000000').click();
});